### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by gavin0x00** [komamj/SingleHandMode#1]
如果用修改LogicalDisplay的方法实现窗口缩小，能不能在黑边空间里添加一个自定义的window？比如下图那样
![onehandmode](https://user-images.githubusercontent.com/17930103/65423211-0d5ac500-de3b-11e9-9d1f-2cdd65793f15.gif)

如有研究过，我可以有偿向您请教，谢谢

**Comment by komamj** [comment]
可以，需要修改native咯吧。
